### ISSUE TITLE
brew services not working on one of my machine

### ISSUE THREAD

**Issue by yqrashawn** [koekeishiya/chunkwm#420]
Same configuration file. Works fine when not using brew services, won't work using brew services. Empty log file. 
It start tons of `chunkc` process

```
Rashawn          10193  29.1  0.0  2447108    756   ??  R     5:33PM   3:24.58 /usr/local/bin/chunkc tiling::window --focus south
Rashawn          10177  27.9  0.0  2448132    768   ??  R     5:33PM   3:25.94 /usr/local/bin/chunkc tiling::window --focus south
Rashawn          10179  27.6  0.0  2447108    756   ??  R     5:33PM   3:25.72 /usr/local/bin/chunkc tiling::window --focus north
Rashawn          10187  26.6  0.0  2445060    732   ??  R     5:33PM   3:25.00 /usr/local/bin/chunkc tiling::window --focus south
Rashawn          11141  26.5  0.0  2447108    756   ??  R     5:41PM   0:55.02 /usr/local/bin/chunkc tiling::window --focus south
Rashawn          10171  26.4  0.0  2446084    744   ??  R     5:33PM   3:26.33 /usr/local/bin/chunkc tiling::window --focus west
Rashawn          10157  26.4  0.0  2444036    720   ??  R     5:33PM   3:27.80 /usr/local/bin/chunkc tiling::window --focus west
Rashawn          10153  26.4  0.0  2466564    804   ??  R     5:33PM   3:28.98 /usr/local/bin/chunkc tiling::window --focus north
Rashawn          11144  26.3  0.0  2447108    756   ??  R     5:41PM   0:54.90 /usr/local/bin/chunkc tiling::window --focus north
Rashawn          10159  26.0  0.0  2446084    744   ??  R     5:33PM   3:27.53 /usr/local/bin/chunkc tiling::window --focus west
Rashawn          10173  25.8  0.0  2446084    744   ??  R     5:33PM   3:26.26 /usr/local/bin/chunkc tiling::window --focus west
Rashawn          10165  25.8  0.0  2445060    732   ??  R     5:33PM   3:26.94 /usr/local/bin/chunkc tiling::window --focus west
Rashawn          11139  25.6  0.0  2448132    768   ??  R     5:41PM   0:55.15 /usr/local/bin/chunkc tiling::window --focus north
Rashawn          10185  25.6  0.0  2448132    768   ??  R     5:33PM   3:25.23 /usr/local/bin/chunkc tiling::window --focus north
Rashawn          11147  25.6  0.0  2434820    700   ??  R     5:41PM   0:54.93 /usr/local/bin/chunkc tiling::window --focus south
Rashawn          10163  25.6  0.0  2446084    744   ??  R     5:33PM   3:27.14 /usr/local/bin/chunkc tiling::window --focus north
Rashawn          11131  25.6  0.0  2446084    744   ??  R     5:41PM   0:55.09 /usr/local/bin/chunkc tiling::window --focus south
Rashawn          10181  25.4  0.0  2445060    732   ??  R     5:33PM   3:25.71 /usr/local/bin/chunkc tiling::window --focus west
Rashawn          11230  25.3  0.0  2438916    748   ??  R     5:41PM   0:52.45 chunkc core::log_level debug
Rashawn          10183  25.3  0.0  2445060    732   ??  R     5:33PM   3:25.52 /usr/local/bin/chunkc tiling::window --focus south
Rashawn          10189  25.3  0.0  2448132    768   ??  R     5:33PM   3:24.80 /usr/local/bin/chunkc tiling::window --focus north
Rashawn          10191  25.3  0.0  2448132    768   ??  R     5:33PM   3:24.66 /usr/local/bin/chunkc tiling::window --focus south
Rashawn          10155  25.1  0.0  2445060    732   ??  R     5:33PM   3:28.38 /usr/local/bin/chunkc tiling::window --focus south
Rashawn          10175  25.0  0.0  2446084    744   ??  R     5:33PM   3:26.21 /usr/local/bin/chunkc tiling::window --focus east
Rashawn          10161  24.8  0.0  2447108    756   ??  R     5:33PM   3:27.31 /usr/local/bin/chunkc tiling::window --focus west
Rashawn          10167  24.8  0.0  2447108    756   ??  R     5:33PM   3:26.85 /usr/local/bin/chunkc tiling::window --focus west
Rashawn          11149  24.3  0.0  2448132    768   ??  R     5:41PM   0:54.89 /usr/local/bin/chunkc tiling::window --focus north
Rashawn          10169  24.1  0.0  2447108    756   ??  R     5:33PM   3:26.61 /usr/local/bin/chunkc tiling::window --focus west
Rashawn          10151  23.9  0.0  2444036    720   ??  R     5:33PM   3:29.26 /usr/local/bin/chunkc tiling::window --focus south

```

brew services works fine on my other machines.

**Comment by yqrashawn** [comment]
log from system console when start chunkwm with `brew services start chunkwm`
```
5/23/18 5:53:32.095 PM launchservicesd[88]: SecTaskLoadEntitlements failed error=22
5/23/18 5:53:32.100 PM launchservicesd[88]: SecTaskLoadEntitlements failed error=22
5/23/18 5:53:32.127 PM launchservicesd[88]: SecTaskLoadEntitlements failed error=22
5/23/18 5:53:32.132 PM tccd[277]: SecTaskLoadEntitlements failed error=22
5/23/18 5:53:32.134 PM tccd[277]: SecTaskLoadEntitlements failed error=22
5/23/18 5:53:32.136 PM iTerm2[299]: SecTaskLoadEntitlements failed error=22
5/23/18 5:53:32.136 PM iTerm2[299]: SecTaskLoadEntitlements failed error=22
5/23/18 5:53:32.136 PM iTerm2[299]: SecTaskLoadEntitlements failed error=22
5/23/18 5:53:32.138 PM tccd[277]: SecTaskLoadEntitlements failed error=22
5/23/18 5:53:32.140 PM Mail[307]: SecTaskLoadEntitlements failed error=22
5/23/18 5:53:32.140 PM Mail[307]: SecTaskLoadEntitlements failed error=22
5/23/18 5:53:32.140 PM Mail[307]: SecTaskLoadEntitlements failed error=22
5/23/18 5:53:32.141 PM tccd[277]: SecTaskLoadEntitlements failed error=22
5/23/18 5:53:32.143 PM Discord[312]: SecTaskLoadEntitlements failed error=22
5/23/18 5:53:32.144 PM Discord[312]: SecTaskLoadEntitlements failed error=22
5/23/18 5:53:32.144 PM Discord[312]: SecTaskLoadEntitlements failed error=22
5/23/18 5:53:32.145 PM tccd[277]: SecTaskLoadEntitlements failed error=22
5/23/18 5:53:32.147 PM Dash[325]: SecTaskLoadEntitlements failed error=22
5/23/18 5:53:32.147 PM Dash[325]: SecTaskLoadEntitlements failed error=22
5/23/18 5:53:32.147 PM Dash[325]: SecTaskLoadEntitlements failed error=22
5/23/18 5:53:32.148 PM tccd[277]: SecTaskLoadEntitlements failed error=22
5/23/18 5:53:32.150 PM Finder[333]: SecTaskLoadEntitlements failed error=22
5/23/18 5:53:32.150 PM Finder[333]: SecTaskLoadEntitlements failed error=22
5/23/18 5:53:32.150 PM Finder[333]: SecTaskLoadEntitlements failed error=22
```

**Comment by yqrashawn** [comment]
chunkwm version 864ee46
macos 10.11.5 (15F34)

**Comment by crisidev** [comment]
Are you 100% sure about the chunkwm version? This looks like the transient issue happening with 0.3.7 where you had calls to chunkc in your chunkwmrc (different from chunkc set and chunkc core) which are not put in background with &. 

It as been resolved with 0.3.8. Do you mind to fully uninstall and reinstall chunkwm?

**Comment by yqrashawn** [comment]
Pretty sure, and I reinstalled just know, `which chunkwm` leads to `/usr/local/bin/chunkwm` and then leads to `/usr/local/Cellar/chunkwm/HEAD-864ee46/bin/chunkwm`. 


Still won't work when start with `brew services`

**Comment by spiermar** [comment]
Another detail. If I start `chunkwm`, with `brew service`, but with an empty `.chunkwmrc` file, then manually execute the `chunkc` commands in my original `rc` file, it works fine. Apparently something is preventing `chunkc` from running via `launchctl`.

**Comment by spiermar** [comment]
Another piece of information. With `chunkwm` running fine, the `chunkc` commands (move, swap, etc) sent by `skhd`, when started by `brew services`, run fine, but the process gets stuck at the same point.
This suggests that `chunkwm` is receiving the messages, doing what needs to be done, but either not writing data back to the socket or `chunkc` is not able to read it.

**Comment by spiermar** [comment]
`poll` is receiving events and entering the loop, just not `POLLIN` events. Couldn't figure out why yet, but I have a quick workaround (not a fix!) in https://github.com/koekeishiya/chunkwm/compare/master...spiermar:master.
Tested the patch and is working for now.
Also tested this on another computer with 10.12.6, but on that one, the issue was not presented. So it might be related to 10.11.x or some configuration.

**Comment by yqrashawn** [comment]
i currently running a watch process to clear chunks process every 5 sec. XD

Martin Spier <notifications@github.com>于2018年6月30日 周六下午12:50写道：
